import Foundation

// MARK: - Model Portfolio

struct ModelPortfolio: Codable, Identifiable, Hashable {
    let id: UUID
    let name: String
    let strategy: String
    let description: String?
    let universe: [String]
    let startingNav: Double
    let assetClass: String
    let benchmark: String?
    let displayOrder: Int?
    let createdAt: Date?

    var isCore: Bool { strategy == "core" }
    var isEdge: Bool { strategy == "edge" }
    var isAlpha: Bool { strategy == "alpha" }

    /// Asset class helpers. Crypto portfolios are systematic (signal-driven);
    /// stock portfolios are curated (target-allocation driven).
    var isCrypto: Bool { assetClass == "crypto" }
    var isStock: Bool { assetClass == "stock" }

    enum CodingKeys: String, CodingKey {
        case id, name, strategy, description, universe, benchmark
        case startingNav = "starting_nav"
        case assetClass = "asset_class"
        case displayOrder = "display_order"
        case createdAt = "created_at"
    }

    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        name = try container.decode(String.self, forKey: .name)
        strategy = try container.decode(String.self, forKey: .strategy)
        description = try container.decodeIfPresent(String.self, forKey: .description)
        universe = try container.decodeIfPresent([String].self, forKey: .universe) ?? []
        startingNav = try container.decodeIfPresent(Double.self, forKey: .startingNav) ?? 50000
        // Default to crypto for backward compatibility with rows created before asset_class existed
        assetClass = try container.decodeIfPresent(String.self, forKey: .assetClass) ?? "crypto"
        benchmark = try container.decodeIfPresent(String.self, forKey: .benchmark)
        displayOrder = try container.decodeIfPresent(Int.self, forKey: .displayOrder)
        createdAt = try container.decodeIfPresent(Date.self, forKey: .createdAt)
    }
}

// MARK: - NAV Snapshot

struct ModelPortfolioNav: Codable, Identifiable, Hashable {
    let id: UUID
    let portfolioId: UUID
    let navDate: String
    let nav: Double
    let allocations: [String: AllocationDetail]
    let btcSignal: String?
    let btcRiskLevel: Double?
    let btcRiskCategory: String?
    let goldSignal: String?
    let macroRegime: String?
    let dominantAlt: String?
    let signalContext: SignalContext?
    let createdAt: Date?

    var returnPct: Double {
        ((nav / 50000) - 1) * 100
    }

    /// True for rows generated by historical backfill (pre-launch, simulated history)
    var isBackfilled: Bool { signalContext?.backfilled == true }

    enum CodingKeys: String, CodingKey {
        case id, nav, allocations
        case portfolioId = "portfolio_id"
        case navDate = "nav_date"
        case btcSignal = "btc_signal"
        case btcRiskLevel = "btc_risk_level"
        case btcRiskCategory = "btc_risk_category"
        case goldSignal = "gold_signal"
        case macroRegime = "macro_regime"
        case dominantAlt = "dominant_alt"
        case signalContext = "signal_context"
        case createdAt = "created_at"
    }

    /// Generic market context for stock portfolio NAV rows
    struct SignalContext: Codable, Hashable {
        let backfilled: Bool?
        let vixSignal: String?
        let vixScore: Double?
        let leadingSectors: [String]?

        enum CodingKeys: String, CodingKey {
            case backfilled
            case vixSignal = "vix_signal"
            case vixScore = "vix_score"
            case leadingSectors = "leading_sectors"
        }
    }

    struct AllocationDetail: Codable, Hashable {
        let pct: Double
        let value: Double?
        let qty: Double?
        let entryPrice: Double?

        /// P&L percentage since entry (nil for stablecoins/gold or missing entry price)
        var pnlPct: Double? {
            guard let entry = entryPrice, let currentValue = value, let currentQty = qty,
                  entry > 0, currentQty > 0 else { return nil }
            let currentPrice = currentValue / currentQty
            return ((currentPrice - entry) / entry) * 100
        }

        init(from decoder: Decoder) throws {
            // Handle both formats: {pct, value, qty, entry_price} or raw number
            if let container = try? decoder.container(keyedBy: CodingKeys.self) {
                pct = try container.decode(Double.self, forKey: .pct)
                value = try container.decodeIfPresent(Double.self, forKey: .value)
                qty = try container.decodeIfPresent(Double.self, forKey: .qty)
                entryPrice = try container.decodeIfPresent(Double.self, forKey: .entryPrice)
            } else {
                // Raw number (backfill format: {"BTC": 60.0})
                let single = try decoder.singleValueContainer()
                pct = try single.decode(Double.self)
                value = nil
                qty = nil
                entryPrice = nil
            }
        }

        enum CodingKeys: String, CodingKey {
            case pct, value, qty
            case entryPrice = "entry_price"
        }
    }
}

// MARK: - Trade Log

struct MarketContext: Codable, Hashable {
    let headlines: [String]?
    let events: [String]?

    var isEmpty: Bool {
        (headlines ?? []).isEmpty && (events ?? []).isEmpty
    }
}

struct ModelPortfolioTrade: Codable, Identifiable, Hashable {
    let id: UUID
    let portfolioId: UUID
    let tradeDate: String
    let trigger: String
    let fromAllocation: [String: Double]
    let toAllocation: [String: Double]
    let marketContext: MarketContext?
    let createdAt: Date?

    enum CodingKeys: String, CodingKey {
        case id, trigger
        case portfolioId = "portfolio_id"
        case tradeDate = "trade_date"
        case fromAllocation = "from_allocation"
        case toAllocation = "to_allocation"
        case marketContext = "market_context"
        case createdAt = "created_at"
    }
}

// MARK: - Benchmark NAV

struct BenchmarkNav: Codable, Identifiable, Hashable {
    let id: UUID
    let navDate: String
    let spyPrice: Double
    let nav: Double
    let createdAt: Date?

    var returnPct: Double {
        ((nav / 50000) - 1) * 100
    }

    enum CodingKeys: String, CodingKey {
        case id, nav
        case navDate = "nav_date"
        case spyPrice = "spy_price"
        case createdAt = "created_at"
    }
}

// MARK: - Risk History

struct ModelPortfolioRiskHistory: Codable, Identifiable, Hashable {
    let id: UUID
    let asset: String
    let riskDate: String
    let riskLevel: Double
    let price: Double
    let fairValue: Double
    let deviation: Double
    let createdAt: Date?

    var riskCategory: String {
        if riskLevel < 0.20 { return "Very Low Risk" }
        if riskLevel < 0.40 { return "Low Risk" }
        if riskLevel < 0.55 { return "Neutral" }
        if riskLevel < 0.70 { return "Elevated Risk" }
        if riskLevel < 0.90 { return "High Risk" }
        return "Extreme Risk"
    }

    enum CodingKeys: String, CodingKey {
        case id, asset, price, deviation
        case riskDate = "risk_date"
        case riskLevel = "risk_level"
        case fairValue = "fair_value"
        case createdAt = "created_at"
    }
}
