name: ArkLine
options:
  bundleIdPrefix: com.arkline
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.9"
    INFOPLIST_KEY_CFBundleDisplayName: "ArkLine"
    INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.finance"

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  ArkLine:
    type: application
    platform: iOS
    sources:
      - path: App
      - path: Core
      - path: Data
      - path: Domain
      - path: Features
      - path: SharedComponents
    resources:
      - path: Resources
        optional: true
    settings:
      base:
        INFOPLIST_FILE: Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.arkline.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: Supabase
