import SwiftUI

struct RundownSlideView: View {
    let data: RundownSlideData
    let title: String
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        VStack(alignment: .leading, spacing: ArkSpacing.lg) {
            SlideHeader(title: title)

            Text(data.narrative)
                .font(AppFonts.body14)
                .foregroundColor(AppColors.textPrimary(colorScheme).opacity(0.8))
                .lineSpacing(7)
                .fixedSize(horizontal: false, vertical: true)

            Text("Generated by Arkline")
                .font(AppFonts.caption12)
                .foregroundColor(AppColors.textSecondary.opacity(0.5))
                .padding(.top, ArkSpacing.sm)
        }
    }
}

// MARK: - Shared Slide Header

struct SlideHeader: View {
    let title: String
    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        VStack(alignment: .leading, spacing: ArkSpacing.sm) {
            Text(title.uppercased())
                .font(AppFonts.interFont(size: 11, weight: .semibold))
                .foregroundColor(AppColors.accent.opacity(0.6))
                .tracking(1.5)

            Rectangle()
                .fill(AppColors.textPrimary(colorScheme).opacity(0.08))
                .frame(height: 1)
        }
    }
}
