-- Add short_rationale column for signal card display
-- One-sentence explanation of why the signal was chosen, shown on card previews.

ALTER TABLE trade_signals
ADD COLUMN IF NOT EXISTS short_rationale text DEFAULT NULL;

COMMENT ON COLUMN trade_signals.short_rationale IS
  'One-sentence rationale for the signal, shown on card previews. Generated by Claude alongside the full briefing.';
