-- Closes the related-term chip coverage gap surfaced on 2026-07-27:
-- 71 related_terms strings resolved to nothing, so their chips rendered muted.
--   Part 1: 8 near-misses to existing terms -> aliases
--   Part 2: 63 genuinely missing terms -> new rows
-- House style: plain-language definition, concrete example, related_terms that
-- themselves resolve. `arkline` entries describe the framework without exposing
-- component weights and avoid buy/sell framing.

-- ── Part 1: aliases for chips that already have a term ──────────────────────
UPDATE dictionary SET aliases = aliases || ARRAY['Risk-On / Risk-Off', 'Risk On / Risk Off'] WHERE slug = 'risk-on';
UPDATE dictionary SET aliases = aliases || ARRAY['Risk-Reward'] WHERE slug = 'risk-reward-ratio';
UPDATE dictionary SET aliases = aliases || ARRAY['QE'] WHERE slug = 'quantitative-easing';
UPDATE dictionary SET aliases = aliases || ARRAY['QT'] WHERE slug = 'quantitative-tightening';
UPDATE dictionary SET aliases = aliases || ARRAY['Fed'] WHERE slug = 'federal-reserve';
UPDATE dictionary SET aliases = aliases || ARRAY['M2'] WHERE slug = 'm2-money-supply';
UPDATE dictionary SET aliases = aliases || ARRAY['Bonds'] WHERE slug = 'bond';
UPDATE dictionary SET aliases = aliases || ARRAY['Correction'] WHERE slug = 'market-correction';

-- ── Part 2: new terms ───────────────────────────────────────────────────────
INSERT INTO dictionary (term, definition, category, example, related_terms, slug, aliases) VALUES
('Accumulation', 'Buying steadily into weakness rather than chasing strength, usually over weeks or months. The opposite of distribution.', 'trading', 'Low risk levels are an accumulation window — you add gradually instead of all at once.', ARRAY['DCA','Risk Levels','Distribution'], 'accumulation', '{}'),
('Advance/Decline', 'A breadth measure comparing how many assets are rising versus falling. Strong indexes with weak breadth often mean a rally is carried by only a few names.', 'technical', 'The S&P 500 hit a high but advance/decline was negative — the rally was narrow.', ARRAY['Breadth','S&P 500','Momentum'], 'advance-decline', ARRAY['A/D Line']),
('Bitcoin Dominance', 'Bitcoin''s share of total crypto market cap. Falling dominance while the market rises is the classic altcoin-season signature.', 'crypto', 'Dominance slipped from 58% to 52% as capital rotated into altcoins.', ARRAY['Altcoin Season','Market Cap','Rotation Signal'], 'bitcoin-dominance', ARRAY['BTC Dominance','BTC.D']),
('Block', 'A batch of transactions permanently recorded on a blockchain. Blocks are produced on a schedule — roughly every 10 minutes for Bitcoin.', 'crypto', 'The transaction confirmed once it was included in the next block.', ARRAY['Blockchain','Mining','Hash Rate'], 'block', '{}'),
('Breakout', 'Price pushing decisively through a level that previously capped it. Breakouts that fail and snap back are common, which is why confirmation matters.', 'technical', 'BTC broke out above resistance at $70K on rising volume.', ARRAY['Resistance','Support','Volume'], 'breakout', '{}'),
('Cash Allocation', 'The share of a portfolio held in cash or stablecoins. Cash is a position — it is what lets you buy when risk levels drop.', 'general', 'Raising cash allocation in a high-risk regime leaves room to accumulate later.', ARRAY['Diversification','Risk-Off','Stablecoin'], 'cash-allocation', ARRAY['Cash']),
('China', 'The world''s second-largest economy. Its credit growth, currency policy, and stimulus meaningfully affect global liquidity and commodity demand.', 'macro', 'A Chinese stimulus package lifted copper and risk assets globally.', ARRAY['Liquidity','Commodities','Copper'], 'china', '{}'),
('Circulating Supply', 'The number of coins actually available to trade right now, excluding locked, reserved, or unissued tokens. Market cap is price times circulating supply.', 'crypto', 'A low circulating supply with large unlocks ahead can mean future sell pressure.', ARRAY['Market Cap','Supply','Tokenomics'], 'circulating-supply', '{}'),
('Collateral', 'Assets pledged to back a loan or leveraged position. If the position moves against you far enough, the collateral is liquidated.', 'trading', 'His ETH was posted as collateral, so a sharp drop triggered liquidation.', ARRAY['Leverage','Margin','Liquidation'], 'collateral', '{}'),
('Compliance', 'Operating within the rules set by financial regulators — licensing, reporting, and customer verification.', 'general', 'Exchanges run KYC checks as part of their compliance obligations.', ARRAY['KYC','Regulation','Security'], 'compliance', '{}'),
('Consensus', 'The mechanism by which a blockchain''s participants agree on which transactions are valid, without a central authority.', 'crypto', 'Bitcoin uses proof-of-work consensus; Ethereum switched to proof-of-stake.', ARRAY['Blockchain','Mining','Decentralization'], 'consensus', '{}'),
('Contrarian', 'Positioning against the prevailing crowd — buying when sentiment is fearful, trimming when it is euphoric.', 'trading', 'Extreme fear readings are a classic contrarian setup.', ARRAY['Fear & Greed Index','Capitulation','Sentiment'], 'contrarian', '{}'),
('Credit', 'Borrowed money in the economy. When credit is expanding, risk assets usually have a tailwind; when it tightens, they usually struggle.', 'macro', 'Widening credit spreads warned of stress before equities sold off.', ARRAY['High Yield Spread','Liquidity','Interest Rate'], 'credit', '{}'),
('Daily Briefing', 'Arkline''s once-a-day written summary of what moved, what changed in the signals, and what is on the calendar. Context for the day, not a trade instruction.', 'arkline', 'The briefing flagged a risk-on regime with a CPI print due that afternoon.', ARRAY['Macro Regime','Positioning Signal','Market Deck'], 'daily-briefing', '{}'),
('Death Cross', 'A shorter moving average crossing below a longer one — most commonly the 50-day below the 200-day. Widely watched, and a lagging signal by nature.', 'technical', 'The 50-day crossed under the 200-day, forming a death cross.', ARRAY['SMA','Golden Cross','Bear Market'], 'death-cross', '{}'),
('Decentralization', 'Spreading control across many independent participants rather than one company or authority. It is what makes a blockchain hard to censor or shut down.', 'crypto', 'Thousands of independent nodes are what keep Bitcoin decentralized.', ARRAY['Blockchain','Consensus','DeFi'], 'decentralization', '{}'),
('Diamond Hands', 'Slang for holding through heavy volatility rather than selling into fear.', 'crypto', 'He had diamond hands through the 60% drawdown.', ARRAY['HODL','Capitulation','FUD'], 'diamond-hands', '{}'),
('Distribution', 'Selling gradually into strength, typically by larger holders, while retail buys the rally. The opposite of accumulation.', 'trading', 'Rising price on fading volume can hint at distribution.', ARRAY['Accumulation','Whale','Volume'], 'distribution', '{}'),
('Economic Data', 'Scheduled government and industry releases — inflation, jobs, growth — that move markets because they shape rate expectations.', 'macro', 'A hot CPI print sent yields higher within seconds of release.', ARRAY['CPI','NFP','GDP'], 'economic-data', '{}'),
('Economic Growth', 'The rate at which an economy is expanding, usually measured by GDP. Strong growth supports earnings; weak growth raises recession risk.', 'macro', 'Growth held up while inflation cooled — the backdrop risk assets like most.', ARRAY['GDP','Recession','Risk-On'], 'economic-growth', '{}'),
('EMA', 'Exponential Moving Average. Like an SMA but weighted toward recent prices, so it turns faster.', 'technical', 'The 21-week EMA is one half of the bull market support band.', ARRAY['SMA','Bull Market Bands','Momentum'], 'ema', ARRAY['Exponential Moving Average']),
('Employment', 'How many people are working. Strong employment supports spending but can keep central banks cautious about cutting rates.', 'macro', 'A strong jobs report pushed rate-cut expectations further out.', ARRAY['NFP','Federal Reserve','Economic Data'], 'employment', ARRAY['Jobs']),
('Ethereum', 'The largest smart-contract blockchain, and the settlement layer most of DeFi is built on. Its native asset is ETH.', 'crypto', 'Most stablecoins and DeFi protocols settle on Ethereum.', ARRAY['Smart Contract','DeFi','Gas'], 'ethereum', ARRAY['ETH']),
('Exchange', 'A venue where assets are bought and sold. Centralized exchanges hold your assets; decentralized ones let you trade from your own wallet.', 'crypto', 'He moved funds off the exchange into self-custody.', ARRAY['Order Book','Liquidity','DeFi'], 'exchange', '{}'),
('Fibonacci', 'A set of ratios — 0.382, 0.5, 0.618, 0.786 — used to map where a pullback might find support before the trend resumes.', 'technical', 'Price retraced to the 0.618 Fibonacci level and bounced.', ARRAY['Fibonacci Retracement','Golden Pocket','Support'], 'fibonacci', '{}'),
('Fully Diluted Valuation', 'What a token would be worth if every coin that will ever exist were circulating today. A large gap versus market cap signals future dilution.', 'crypto', 'Market cap looked small, but FDV was 5x higher due to locked tokens.', ARRAY['Market Cap','Circulating Supply','Tokenomics'], 'fully-diluted-valuation', ARRAY['FDV']),
('Futures', 'Contracts to buy or sell an asset at a set price later. Perpetual futures never expire and are the dominant crypto derivative.', 'trading', 'Funding rates come from perpetual futures, not spot markets.', ARRAY['Funding Rate','Leverage','Open Interest'], 'futures', ARRAY['Perpetuals','Perps']),
('Golden Cross', 'A shorter moving average crossing above a longer one — usually the 50-day above the 200-day. Read as trend confirmation, and it lags.', 'technical', 'The 50-day crossed above the 200-day, forming a golden cross.', ARRAY['SMA','Death Cross','Bull Market'], 'golden-cross', '{}'),
('Guidance', 'A company''s own forecast for coming quarters. Guidance often moves a stock more than the results just reported.', 'general', 'Earnings beat, but weak guidance sent the stock lower.', ARRAY['Earnings','Revenue','Valuation'], 'guidance', '{}'),
('Income', 'Cash an investment pays you — dividends, staking rewards, or bond coupons — separate from price appreciation.', 'general', 'Treasuries paying 5% made cash a real income option again.', ARRAY['Dividend','Yield','Fixed Income'], 'income', '{}'),
('Index', 'A basket tracking a slice of the market, used as a benchmark. The S&P 500 and Nasdaq are the most watched.', 'general', 'Most active funds fail to beat their index over a decade.', ARRAY['S&P 500','Nasdaq','ETF'], 'index', '{}'),
('Layer 2', 'A network built on top of a base blockchain to make transactions cheaper and faster while still settling to the main chain.', 'crypto', 'Layer 2s cut Ethereum transaction costs dramatically.', ARRAY['Ethereum','Gas','Protocol'], 'layer-2', ARRAY['L2']),
('Long-Term', 'A holding horizon measured in years, where cycle position matters more than any single week''s move.', 'general', 'Long-term holders treat drawdowns as accumulation windows.', ARRAY['HODL','DCA','Risk Levels'], 'long-term', '{}'),
('Lump Sum', 'Investing all at once instead of spreading purchases over time. Historically it wins more often, but it hurts far more if you mistime it.', 'trading', 'He chose DCA over a lump sum to reduce timing risk.', ARRAY['DCA','Smart DCA','Risk Management'], 'lump-sum', '{}'),
('Margin Call', 'A demand for more collateral when a leveraged position moves against you. Ignore it and the position gets liquidated.', 'trading', 'The drop triggered a margin call across over-leveraged longs.', ARRAY['Margin','Liquidation','Collateral'], 'margin-call', '{}'),
('Momentum', 'The speed and persistence of a price move. Strong momentum tends to continue until it visibly stalls.', 'technical', 'Momentum faded as each new high came on lighter volume.', ARRAY['RSI','Momentum Map','Volume'], 'momentum', '{}'),
('On-Chain', 'Data read directly from a blockchain — wallet flows, holder behaviour, supply in profit — rather than from exchanges or price feeds.', 'crypto', 'On-chain data showed long-term holders were still accumulating.', ARRAY['Blockchain','Whale','Supply'], 'on-chain', '{}'),
('Order Book', 'The live list of buy and sell orders at each price. A thin book means larger trades move price more.', 'trading', 'The thin order book turned a modest sell into a sharp drop.', ARRAY['Liquidity','Slippage','Exchange'], 'order-book', '{}'),
('Overbought', 'A condition where price has risen far and fast enough that momentum indicators flag it as stretched. It signals stretch, not a top.', 'technical', 'RSI above 70 marks overbought, though strong trends stay there for weeks.', ARRAY['RSI','Oversold','Momentum'], 'overbought', '{}'),
('Oversold', 'A condition where price has fallen far and fast enough to look stretched to the downside. It signals stretch, not a bottom.', 'technical', 'RSI below 30 marks oversold, but assets can stay oversold in a downtrend.', ARRAY['RSI','Overbought','Capitulation'], 'oversold', '{}'),
('P&L', 'Profit and loss — what a position has actually made or lost. Unrealised until you close it.', 'trading', 'The runner half was up 12% in unrealised P&L.', ARRAY['ROI','Runner','Take Profit'], 'p-and-l', ARRAY['PnL','P/L','Profit and Loss']),
('Portfolio', 'Everything you hold, viewed as one book. What matters is how the pieces behave together, not any single position.', 'general', 'Two assets that always move together add less diversification than they appear to.', ARRAY['Diversification','Correlation','Cash Allocation'], 'portfolio', '{}'),
('Position Size', 'How much capital a single trade or holding gets. Size, not entry price, is what usually decides whether a loss is survivable.', 'trading', 'Risking 1% per trade means a string of losses stays manageable.', ARRAY['Risk Management','Leverage','Stop Loss'], 'position-size', ARRAY['Sizing']),
('Protocol', 'The rule set a blockchain or application runs on — how transactions work, who validates, how fees are charged.', 'crypto', 'A protocol upgrade changed how fees were burned.', ARRAY['Blockchain','Smart Contract','DeFi'], 'protocol', '{}'),
('Psychology', 'The emotional side of investing — fear, greed, impatience — which is usually what turns a sound plan into a bad outcome.', 'trading', 'Selling the bottom is a psychology problem, not an analysis problem.', ARRAY['FOMO','FUD','Capitulation'], 'psychology', '{}'),
('Pullback', 'A temporary move against the prevailing trend. Healthy uptrends pull back regularly without breaking.', 'technical', 'BTC pulled back to its 21-week EMA and resumed higher.', ARRAY['Support','Uptrend','Fibonacci Retracement'], 'pullback', '{}'),
('QQQ', 'The ETF tracking the Nasdaq 100. Often used as shorthand for how large-cap tech is trading.', 'general', 'Crypto has tracked QQQ closely in risk-on stretches.', ARRAY['Nasdaq','ETF','Correlation'], 'qqq', '{}'),
('Rally', 'A sustained move higher over days or weeks. Whether it lasts usually depends on breadth and volume.', 'general', 'The rally broadened out beyond a handful of megacaps.', ARRAY['Breakout','Breadth','Bull Market'], 'rally', '{}'),
('Regulation', 'Government rules governing how assets can be issued, traded, and custodied. Regulatory shifts can reprice an entire sector overnight.', 'general', 'ETF approval was a regulatory turning point for crypto access.', ARRAY['Compliance','KYC','ETF'], 'regulation', '{}'),
('Relative Strength', 'How one asset is performing against another or against the broader market — the basis for rotation decisions.', 'technical', 'BTC showed relative strength against equities all quarter.', ARRAY['Rotation Signal','Sector Rotation','Momentum'], 'relative-strength', '{}'),
('Revenue', 'The total money a business takes in before costs. Growth in revenue matters more than its level.', 'general', 'Revenue grew 20% but margins compressed.', ARRAY['Earnings','Guidance','Valuation'], 'revenue', ARRAY['Top Line']),
('Risk Management', 'Deciding in advance how much you can lose on a position and sizing accordingly. It is the part of a strategy that determines survival.', 'trading', 'Position size and a predefined stop are risk management; a price target is not.', ARRAY['Position Size','Stop Loss','Invalidation'], 'risk-management', '{}'),
('Security', 'In investing, a tradable financial asset. In crypto, it also means protecting your keys and accounts from theft.', 'general', 'Whether a token counts as a security is a regulatory question.', ARRAY['Regulation','Compliance','KYC'], 'security', '{}'),
('Sentiment', 'How bullish or bearish participants feel right now. Extremes tend to matter more than the middle.', 'trading', 'Sentiment hit extreme fear right as price stabilised.', ARRAY['Fear & Greed Index','Contrarian','FOMO'], 'sentiment', '{}'),
('Spread', 'The gap between the best buy and sell price. Wide spreads mean thin liquidity and worse fills.', 'trading', 'Spreads widened during the volatility spike.', ARRAY['Liquidity','Slippage','Order Book'], 'spread', '{}'),
('Supply', 'How much of an asset exists or is available. Fixed or shrinking supply against steady demand is the core of the scarcity argument.', 'crypto', 'Bitcoin''s supply is capped at 21 million coins.', ARRAY['Circulating Supply','Halving','Tokenomics'], 'supply', '{}'),
('Take Profit', 'Closing part or all of a position to lock in gains. Doing it in stages avoids the all-or-nothing exit problem.', 'trading', 'She took profit on half at T1 and trailed the rest.', ARRAY['Target 1 (T1)','Runner','Consider-Profit Zone'], 'take-profit', ARRAY['TP']),
('Token', 'A digital asset issued on an existing blockchain, as opposed to a chain''s own native coin.', 'crypto', 'Most DeFi tokens are issued on Ethereum.', ARRAY['Ethereum','Smart Contract','Tokenomics'], 'token', '{}'),
('Tokenomics', 'How a token''s supply, issuance, unlocks, and incentives are designed. Weak tokenomics can sink a good product.', 'crypto', 'Heavy unlocks ahead made the tokenomics unattractive despite real usage.', ARRAY['Circulating Supply','Fully Diluted Valuation','Supply'], 'tokenomics', '{}'),
('Uptrend', 'A sequence of higher highs and higher lows. Pullbacks inside an uptrend are normal and often the better entries.', 'technical', 'The uptrend held as each pullback made a higher low.', ARRAY['Pullback','Support','Bull Market'], 'uptrend', '{}'),
('USD', 'The US dollar, the world''s reserve currency. A stronger dollar generally tightens global conditions and pressures risk assets.', 'macro', 'A rising dollar has been a persistent headwind for crypto.', ARRAY['DXY','Liquidity','Risk-Off'], 'usd', ARRAY['Dollar','US Dollar']),
('Valuation', 'What you are paying relative to what you are getting — earnings, cash flow, or usage. High valuations raise the bar for future returns.', 'general', 'The index kept rising even as valuations stretched.', ARRAY['P/E Ratio','Earnings','Fundamental Analysis'], 'valuation', '{}'),
('Volatility', 'How much and how fast price moves. Higher volatility means wider ranges and demands smaller position sizes.', 'trading', 'Volatility spiked, so the same trade needed a wider stop and less size.', ARRAY['VIX','Volatility Regime','Position Size'], 'volatility', '{}')
ON CONFLICT DO NOTHING;
