-- Macro, fixed income, equities, commodities, FX, and Fed terminology
-- Broadens the dictionary beyond crypto to cover the full investing spectrum

INSERT INTO dictionary (term, definition, category, example, related_terms) VALUES
  -- Federal Reserve & Monetary Policy
  ('Federal Reserve', 'The central bank of the United States. Controls interest rates, money supply, and acts as lender of last resort. Its decisions move every market — stocks, bonds, crypto, and currencies.', 'macro', 'The Fed raised rates by 0.25% to fight inflation, sending stocks and crypto lower on the announcement.', ARRAY['FOMC','Interest Rate','Quantitative Easing']),
  ('FOMC', 'Federal Open Market Committee. The Fed body that meets 8 times a year to set interest rate policy. FOMC meetings are the most watched events in finance.', 'macro', 'Markets held their breath as the FOMC decided to hold rates steady, sparking a relief rally.', ARRAY['Federal Reserve','Interest Rate','Dot Plot']),
  ('Interest Rate', 'The cost of borrowing money, set by central banks. Higher rates make borrowing expensive (slows economy, bad for risk assets). Lower rates stimulate growth (good for stocks and crypto).', 'macro', 'When the Fed cut rates to near zero in 2020, it fueled a massive rally in stocks and crypto.', ARRAY['Federal Reserve','FOMC','Bonds']),
  ('Quantitative Easing', 'When a central bank creates new money to buy bonds, injecting liquidity into the financial system. Expands money supply, supports asset prices. Often called "money printing."', 'macro', 'The Fed''s QE program in 2020 pumped trillions into markets, driving stocks and crypto to all-time highs.', ARRAY['Quantitative Tightening','Federal Reserve','M2','Liquidity']),
  ('Quantitative Tightening', 'The opposite of QE — the Fed shrinks its balance sheet by letting bonds mature without reinvesting. Removes liquidity from markets, typically bearish for risk assets.', 'macro', 'QT in 2022 drained liquidity and contributed to the bear market in both stocks and crypto.', ARRAY['Quantitative Easing','Federal Reserve','Liquidity']),
  ('Dot Plot', 'A chart showing where each FOMC member expects interest rates to be in the future. Gives markets a roadmap of the Fed''s thinking on rate hikes or cuts.', 'macro', 'The dot plot shifted hawkish — members projected fewer rate cuts than expected, sending markets lower.', ARRAY['FOMC','Interest Rate','Federal Reserve']),
  ('Hawkish', 'A stance favoring higher interest rates and tighter monetary policy to control inflation. Typically bearish for stocks and crypto.', 'macro', 'The Fed chair sounded hawkish in the press conference, warning that inflation remains too high for cuts.', ARRAY['Dovish','Federal Reserve','Interest Rate']),
  ('Dovish', 'A stance favoring lower interest rates and looser monetary policy to stimulate growth. Typically bullish for risk assets.', 'macro', 'Dovish comments from the Fed about potential rate cuts sent stocks rallying 2% in a single session.', ARRAY['Hawkish','Federal Reserve','Interest Rate']),
  ('M2 Money Supply', 'A measure of the total money in circulation — cash, checking deposits, savings, and money market funds. Expanding M2 historically correlates with rising asset prices.', 'macro', 'Global M2 money supply hit a new high, providing a tailwind for Bitcoin and risk assets.', ARRAY['Liquidity','Quantitative Easing','Federal Reserve']),
  ('Fed Funds Rate', 'The interest rate at which banks lend to each other overnight. The primary tool the Fed uses to influence the economy. All other rates (mortgages, loans) are derived from this.', 'macro', 'The Fed funds rate at 5.25% made borrowing expensive across the economy, cooling inflation but also growth.', ARRAY['Federal Reserve','FOMC','Interest Rate']),

  -- Fixed Income & Credit
  ('Bond', 'A loan you make to a government or corporation in exchange for regular interest payments and return of principal at maturity. Bonds are considered safer than stocks.', 'macro', 'When investors get scared, they sell stocks and buy Treasury bonds — that''s why bond prices rise during panics.', ARRAY['Yield','Treasury','Fixed Income']),
  ('Yield', 'The return earned on a bond, expressed as a percentage. When bond prices go up, yields go down (and vice versa). Higher yields attract money away from stocks and crypto.', 'macro', 'The 10-year Treasury yield hit 5%, making bonds competitive with stocks for the first time in years.', ARRAY['Bond','Treasury','Interest Rate']),
  ('Yield Curve', 'A chart showing bond yields across different maturities (2-year, 10-year, 30-year). A normal curve slopes upward. An inverted curve (short rates higher than long) historically predicts recession.', 'macro', 'The yield curve inverted in 2022 — short-term bonds paid more than long-term, signaling recession risk.', ARRAY['Bond','Yield','Recession']),
  ('Treasury', 'A bond issued by the US government. Considered the safest investment in the world. T-Bills (short-term), T-Notes (2-10 years), T-Bonds (20-30 years).', 'macro', 'Flight to safety during the crash pushed Treasury prices higher as investors dumped risky assets.', ARRAY['Bond','Yield','TLT']),
  ('TLT', 'The iShares 20+ Year Treasury Bond ETF. A popular way to trade long-term US government bonds. Rises when yields fall, drops when yields rise.', 'macro', 'TLT rallied 8% as markets priced in rate cuts — long-duration bonds benefit most from falling yields.', ARRAY['Treasury','Bond','Yield']),
  ('High Yield Spread', 'The difference between junk bond yields and Treasury yields. Widens when credit stress increases (risk-off), tightens when conditions improve (risk-on). A key risk appetite indicator.', 'macro', 'High yield spreads widened sharply, signaling that credit markets were pricing in economic stress before equities reacted.', ARRAY['Bond','Credit','Risk-Off']),
  ('Credit Default Swap', 'Insurance against a borrower defaulting on debt. Rising CDS prices signal growing concern about credit risk. Used as a gauge of financial system stress.', 'macro', 'Bank CDS spreads spiked during the SVB crisis, signaling fear of contagion across the financial system.', ARRAY['High Yield Spread','Credit','Risk-Off']),
  ('Fixed Income', 'Investments that pay a fixed return — primarily bonds. Called "fixed" because the interest payments are predetermined. The largest asset class in the world.', 'macro', 'Fixed income markets dwarf equities — the global bond market is over $130 trillion compared to $100 trillion in stocks.', ARRAY['Bond','Yield','Treasury']),
  ('Repo Operations', 'Short-term borrowing between banks using Treasury bonds as collateral. The repo market is the plumbing of the financial system. Stress here can signal broader funding problems.', 'macro', 'Overnight repo rates spiked, indicating funding stress — the Fed had to intervene with emergency liquidity.', ARRAY['Federal Reserve','Liquidity','SOFR']),
  ('SOFR', 'Secured Overnight Financing Rate. The benchmark interest rate for dollar-denominated loans. Replaced LIBOR in 2023. Spikes in SOFR signal funding stress in the banking system.', 'macro', 'SOFR spiking above the Fed''s target range is a warning sign of liquidity tightening in the financial system.', ARRAY['Repo Operations','Interest Rate','Liquidity']),

  -- Equities
  ('S&P 500', 'An index of the 500 largest US companies by market cap. The most widely followed benchmark for the US stock market. SPY is the ETF that tracks it.', 'general', 'The S&P 500 hit a new all-time high, signaling broad market strength beyond just tech stocks.', ARRAY['Index','Nasdaq','Dow Jones']),
  ('Nasdaq', 'A stock exchange and index heavily weighted toward technology companies. The Nasdaq Composite includes all stocks listed on the exchange. QQQ tracks the top 100.', 'general', 'The Nasdaq outperformed the S&P 500 as tech stocks led the rally, driven by AI optimism.', ARRAY['S&P 500','Index','QQQ']),
  ('Dow Jones', 'The Dow Jones Industrial Average (DJIA). An index of 30 large US companies. The oldest and most recognizable market index, though less representative than the S&P 500.', 'general', 'The Dow dropped 500 points as industrial and financial stocks sold off on recession fears.', ARRAY['S&P 500','Nasdaq','Index']),
  ('P/E Ratio', 'Price-to-Earnings ratio. A stock''s price divided by its earnings per share. Higher P/E means investors are paying more per dollar of earnings. Used to gauge if a stock is overvalued or undervalued.', 'general', 'Tesla trades at a 60x P/E while the S&P 500 average is 20x — investors are paying a premium for growth expectations.', ARRAY['Valuation','Earnings','Market Cap']),
  ('Earnings', 'A company''s profits reported quarterly. Earnings season (Jan, Apr, Jul, Oct) drives major stock price moves. "Beat" means actual earnings exceeded analyst expectations.', 'general', 'Apple beat earnings by 8%, sending the stock up 5% after hours.', ARRAY['P/E Ratio','Revenue','Guidance']),
  ('Dividend', 'A portion of company profits paid to shareholders, usually quarterly. Dividend-paying stocks provide income in addition to potential price appreciation.', 'general', 'The stock pays a 3% annual dividend — meaning $3,000/year on a $100,000 investment.', ARRAY['Yield','Income','Blue Chip']),
  ('Market Correction', 'A decline of 10-20% from recent highs. Corrections are normal and healthy — they reset overextended valuations. Not the same as a bear market (20%+ decline).', 'general', 'The S&P 500 entered correction territory after falling 12% from its peak, but recovered within 6 weeks.', ARRAY['Bear Market','Volatility','Pullback']),
  ('Blue Chip', 'A large, well-established, financially stable company with a history of reliable performance. Think Apple, Microsoft, Johnson & Johnson.', 'general', 'Blue chip stocks held up better during the selloff — investors rotated from speculative names into quality.', ARRAY['Market Cap','Dividend','S&P 500']),
  ('IPO', 'Initial Public Offering. When a private company first sells shares to the public on a stock exchange. Often generates hype but the first-day pop doesn''t always hold.', 'general', 'The IPO priced at $30, opened at $45, but settled back to $32 within a month — typical for overhyped debuts.', ARRAY['Market Cap','ICO','Valuation']),
  ('ETF', 'Exchange-Traded Fund. A basket of assets (stocks, bonds, commodities) that trades like a single stock. SPY (S&P 500), QQQ (Nasdaq), GLD (gold) are popular examples.', 'general', 'Instead of buying 500 individual stocks, you can buy one share of SPY and own the entire S&P 500.', ARRAY['Index','S&P 500','Diversification']),
  ('Short Selling', 'Borrowing shares and selling them, expecting to buy them back cheaper later. Profit from falling prices. Risk is theoretically unlimited since price can rise infinitely.', 'trading', 'Short sellers targeted the stock after the earnings miss — short interest reached 25% of the float.', ARRAY['Long/Short','Short Squeeze','Margin']),
  ('Short Squeeze', 'When a heavily shorted stock rises sharply, forcing short sellers to buy back shares to cover losses — which pushes the price even higher in a feedback loop.', 'trading', 'GameStop''s short squeeze in 2021 sent the stock from $20 to $480 as retail traders forced hedge funds to cover.', ARRAY['Short Selling','Volume','Volatility']),

  -- Commodities
  ('WTI Crude Oil', 'West Texas Intermediate — the benchmark for US oil prices. Oil prices affect inflation, transportation costs, and energy stocks. Traded as CL futures or USO ETF.', 'macro', 'WTI crude spiked to $90/barrel after OPEC cut production, raising inflation concerns and pressuring the Fed.', ARRAY['Commodities','Inflation','OPEC']),
  ('Brent Crude', 'The international benchmark for oil prices, used for about two-thirds of global oil contracts. Typically trades at a slight premium to WTI.', 'macro', 'Brent crude traded at $92 while WTI was at $88 — the spread reflects international supply dynamics.', ARRAY['WTI Crude Oil','Commodities','OPEC']),
  ('Gold', 'The traditional safe-haven asset. Tends to rise during uncertainty, inflation, and currency debasement. Often moves inversely to the US dollar.', 'macro', 'Gold hit $4,800/oz as investors sought safety during geopolitical tensions and dollar weakness.', ARRAY['Safe Haven','Inflation','DXY']),
  ('Silver', 'A precious metal with both investment and industrial demand. More volatile than gold — tends to amplify gold''s moves in both directions.', 'macro', 'Silver rallied 10% on the week as industrial demand from solar panel production combined with safe-haven buying.', ARRAY['Gold','Commodities','Inflation']),
  ('Copper', 'An industrial metal often called "Dr. Copper" because its price reflects global economic health. Rising copper = economic growth expectations. Falling copper = slowdown fears.', 'macro', 'Copper prices surged on Chinese stimulus announcements — the market sees it as a leading indicator of economic recovery.', ARRAY['Commodities','China','Economic Growth']),
  ('OPEC', 'Organization of the Petroleum Exporting Countries. A cartel of oil-producing nations that coordinates production to influence global oil prices.', 'macro', 'OPEC announced surprise production cuts, sending oil prices 8% higher and reigniting inflation fears.', ARRAY['WTI Crude Oil','Commodities','Inflation']),
  ('Commodities', 'Raw materials traded on exchanges — oil, gold, silver, copper, wheat, natural gas. Prices are driven by supply/demand, geopolitics, and economic cycles.', 'macro', 'Commodity prices surged across the board as supply chain disruptions collided with strong demand.', ARRAY['WTI Crude Oil','Gold','Copper']),

  -- FX & Currency
  ('Forex', 'The foreign exchange market where currencies are traded. The largest financial market in the world with $7 trillion in daily volume.', 'macro', 'Forex traders closely watch central bank decisions — rate differentials drive currency movements.', ARRAY['DXY','USD/JPY','EUR/USD']),
  ('USD/JPY', 'The exchange rate between the US dollar and Japanese yen. A key carry trade pair — when the yen weakens sharply, it can trigger global risk-off moves.', 'macro', 'USD/JPY hit 155 as the yen weakened on the Bank of Japan''s ultra-loose policy, pressuring global markets.', ARRAY['Forex','DXY','Carry Trade']),
  ('EUR/USD', 'The exchange rate between the euro and US dollar. The most traded currency pair in the world. Moves inversely to the DXY.', 'macro', 'EUR/USD fell below 1.05 as ECB rate cuts diverged from the Fed''s hold, strengthening the dollar.', ARRAY['Forex','DXY','ECB']),
  ('Carry Trade', 'Borrowing in a low-interest-rate currency (like yen) and investing in higher-yielding assets. Profitable when stable, but violent unwinds can crash global markets.', 'macro', 'The yen carry trade unwind in August 2024 caused a flash crash across global equities and crypto.', ARRAY['USD/JPY','Forex','Risk-Off']),
  ('ECB', 'European Central Bank. The central bank for the eurozone. Its rate decisions affect EUR/USD and European markets, with spillover effects globally.', 'macro', 'The ECB cut rates before the Fed, weakening the euro and strengthening the dollar index.', ARRAY['Federal Reserve','EUR/USD','Interest Rate']),

  -- Inflation & Economic Data
  ('CPI', 'Consumer Price Index. The primary measure of inflation — tracks the average change in prices paid by consumers. Higher CPI = more inflation = hawkish Fed response.', 'macro', 'CPI came in at 3.2%, below the 3.4% estimate — lower-than-expected inflation is bullish for risk assets.', ARRAY['Inflation','PPI','Federal Reserve']),
  ('PPI', 'Producer Price Index. Measures inflation at the wholesale level before it reaches consumers. A leading indicator of future CPI — rising PPI today means higher consumer prices tomorrow.', 'macro', 'PPI rose 0.5% month-over-month, suggesting inflation pressure is building in the supply chain.', ARRAY['CPI','Inflation','Federal Reserve']),
  ('PCE', 'Personal Consumption Expenditures index. The Fed''s preferred inflation measure (not CPI). Core PCE excludes food and energy for a cleaner read on underlying inflation trends.', 'macro', 'Core PCE at 2.8% remains above the Fed''s 2% target, keeping rate cuts off the table for now.', ARRAY['CPI','Inflation','Federal Reserve']),
  ('Inflation', 'The rate at which prices for goods and services increase over time. Moderate inflation (2%) is healthy. High inflation erodes purchasing power and forces central banks to raise rates.', 'macro', 'Inflation peaked at 9.1% in 2022, forcing the Fed into the most aggressive rate hiking cycle in decades.', ARRAY['CPI','Federal Reserve','Interest Rate']),
  ('Recession', 'Commonly defined as two consecutive quarters of negative GDP growth. Recessions bring job losses, lower corporate earnings, and falling asset prices.', 'macro', 'The yield curve inversion in 2022 correctly predicted economic slowdown — it has preceded every recession since 1970.', ARRAY['GDP','Yield Curve','Bear Market']),
  ('GDP', 'Gross Domestic Product. The total value of goods and services produced in a country. The broadest measure of economic health. Positive GDP = growth, negative = contraction.', 'macro', 'GDP growth came in at 2.1%, beating estimates — suggesting the economy is resilient despite tight monetary policy.', ARRAY['Recession','Economic Growth','Federal Reserve']),
  ('NFP', 'Non-Farm Payrolls. The monthly US jobs report showing how many jobs were added or lost. One of the most market-moving economic releases. Strong jobs = hawkish Fed.', 'macro', 'NFP showed 300K jobs added vs 200K expected — strong labor market reduces the odds of near-term rate cuts.', ARRAY['Federal Reserve','Employment','Economic Data']),
  ('Safe Haven', 'An asset that tends to hold or increase in value during market turmoil. Traditional safe havens: US Treasuries, gold, Swiss franc, Japanese yen.', 'macro', 'Gold and Treasuries rallied as safe haven flows picked up during the geopolitical escalation.', ARRAY['Gold','Treasury','Risk-Off']),
  ('Sector Rotation', 'When investors shift money between different stock market sectors based on the economic cycle. Early cycle favors growth/tech, late cycle favors defensives/utilities.', 'general', 'Money rotated from tech into energy and financials as the market shifted to a late-cycle posture.', ARRAY['Economic Growth','Blue Chip','ETF']),
  ('Breadth', 'How many stocks are participating in a market move. Strong breadth = most stocks rising together (healthy). Weak breadth = only a few stocks driving the index (fragile rally).', 'technical', 'The S&P 500 hit a new high but breadth was weak — only the top 10 stocks were up, while 400 were flat or down.', ARRAY['Advance/Decline','Volume','S&P 500']),
  ('Volume', 'The number of shares or contracts traded in a given period. High volume confirms conviction behind a move. Low volume rallies are suspect and often reverse.', 'technical', 'BTC broke above $75K on 3x average volume — the surge in participation confirms the breakout is real.', ARRAY['Open Interest','Breadth','Liquidity']),
  ('Correlation', 'How closely two assets move together. Correlation of +1 = move identically, -1 = move opposite, 0 = no relationship. BTC and tech stocks have become increasingly correlated.', 'general', 'BTC''s correlation with the Nasdaq rose to 0.85 — meaning crypto is trading like a tech stock, not digital gold.', ARRAY['Diversification','Risk-On','Nasdaq']),
  ('Diversification', 'Spreading investments across different assets to reduce risk. The idea is that when one asset falls, others may hold steady or rise.', 'general', 'A portfolio of only Bitcoin has high returns but extreme volatility — diversifying into gold and bonds reduces drawdowns.', ARRAY['Correlation','Portfolio','Risk Management'])
ON CONFLICT (term) DO NOTHING;
