-- Real trade signals generated from Binance data (2026-02-28 to 2026-03-07)
-- Generated by scripts/generate_real_signals.py using exact pipeline logic
-- 12 signals across 6 assets

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '7723ba90-8fef-41c6-8336-1b1eb7c02982', 'BTC', 'buy', 'invalidated',
  69417.9432, 70637.976, 70027.9596,
  71467.61112, 71580.49992, 68962.32840624,
  1.35, 1065.6311937599967,
  TRUE, '{"wick_rejection": true, "volume_spike": false, "consecutive_closes": false}'::jsonb, TRUE,
  70027.9596, 68962.32840624, NULL,
  NULL, NULL, NULL,
  'loss', -1.52, 12,
  '2026-03-06T00:00:00+00:00', '2026-03-06T00:00:00+00:00', '2026-03-09T00:00:00+00:00', '2026-03-06T12:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  'fd8b4827-8b52-41af-9072-3422feacef5f', 'ETH', 'buy', 'target_hit',
  1987.8933, 2028.81254, 2008.3529199999998,
  2052.4507, 2056.17902, 1965.0609982400001,
  1.02, 43.291921759999695,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  2090.0, 2046.7080782400003, 2046.7080782400003,
  '2026-03-02T16:00:00+00:00', 2.2, 1.91,
  'win', 2.05, 8,
  '2026-03-02T12:00:00+00:00', '2026-03-02T12:00:00+00:00', '2026-03-05T12:00:00+00:00', '2026-03-02T20:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '29c6d0dc-98f6-41f2-9789-c8ab520203cb', 'ETH', 'buy', 'invalidated',
  2143.0184600000002, 2143.02756, 2143.02301,
  2219.4491, 2243.62836, 2095.6832922199997,
  1.61, 47.33971778000023,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  2143.02301, 2095.6832922199997, NULL,
  NULL, NULL, NULL,
  'loss', -2.21, 20,
  '2026-03-04T12:00:00+00:00', '2026-03-04T12:00:00+00:00', '2026-03-07T12:00:00+00:00', '2026-03-05T08:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  'a64f119e-6693-444b-9fe1-89d9c36ef5f5', 'SOL', 'buy', 'invalidated',
  87.91518, 89.42714, 88.67116,
  91.27554, 92.03796, 87.06683353999999,
  1.62, 1.60432646000001,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  88.67116, 87.06683353999999, NULL,
  NULL, NULL, NULL,
  'loss', -1.81, 4,
  '2026-03-02T12:00:00+00:00', '2026-03-02T12:00:00+00:00', '2026-03-05T12:00:00+00:00', '2026-03-02T16:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '762c917c-d26f-4f30-aa9c-fdb8503ce686', 'SOL', 'strong_buy', 'invalidated',
  91.27554, 92.03796, 91.65675,
  98.53368, 103.55802, 89.15885858,
  2.75, 2.497891420000002,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  91.65675, 89.15885858, NULL,
  NULL, NULL, NULL,
  'loss', -2.73, 24,
  '2026-03-04T12:00:00+00:00', '2026-03-04T12:00:00+00:00', '2026-03-07T12:00:00+00:00', '2026-03-05T12:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  'a00a541d-dfcc-476f-afd1-2f6ea05aa49a', 'SUI', 'sell', 'target_hit',
  0.9116152000000001, 0.928756, 0.9201856,
  0.9024854, 0.8934576, 0.9378655812,
  1.0, 0.017679981199999917,
  TRUE, '{"wick_rejection": true, "volume_spike": false, "consecutive_closes": true}'::jsonb, TRUE,
  0.8663, 0.8839799811999999, 0.8839799811999999,
  '2026-03-01T16:00:00+00:00', 1.92, 3.93,
  'win', 2.93, 8,
  '2026-03-01T12:00:00+00:00', '2026-03-01T12:00:00+00:00', '2026-03-04T12:00:00+00:00', '2026-03-01T20:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '570888e6-6f5d-4284-8a7b-0473d23cc693', 'SUI', 'sell', 'target_hit',
  0.9023376000000001, 0.9272004, 0.914769,
  0.8934576, 0.8880694, 0.9317115743999999,
  1.26, 0.0169425743999998,
  TRUE, '{"wick_rejection": true, "volume_spike": false, "consecutive_closes": false}'::jsonb, TRUE,
  0.8924, 0.9093425743999998, 0.9093425743999998,
  '2026-03-04T00:00:00+00:00', 2.33, 0.59,
  'win', 1.46, 16,
  '2026-03-03T12:00:00+00:00', '2026-03-03T12:00:00+00:00', '2026-03-06T12:00:00+00:00', '2026-03-04T04:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  'b968620d-24d7-4b83-8b49-47567be3297a', 'SUI', 'buy', 'target_hit',
  0.9553446, 0.9643848, 0.9598647,
  0.9750108000000001, 0.9762018, 0.9493780956000001,
  1.44, 0.010486604399999933,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  0.9931, 0.9826133956, 0.9826133956,
  '2026-03-04T16:00:00+00:00', 1.58, 2.37,
  'win', 1.97, 8,
  '2026-03-04T12:00:00+00:00', '2026-03-04T12:00:00+00:00', '2026-03-07T12:00:00+00:00', '2026-03-04T20:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '77881e92-cac9-457c-aff7-bd5d9f7c9018', 'LINK', 'buy', 'target_hit',
  8.961760000000002, 9.11632, 9.03904,
  9.26044, 9.26044, 8.8734994,
  1.34, 0.16554059999999993,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  9.27, 9.1044594, 9.1044594,
  '2026-03-02T16:00:00+00:00', 2.45, 0.72,
  'win', 1.59, 8,
  '2026-03-02T12:00:00+00:00', '2026-03-02T12:00:00+00:00', '2026-03-05T12:00:00+00:00', '2026-03-02T20:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '6afd891c-e756-4593-ae0c-208790956aec', 'LINK', 'strong_buy', 'invalidated',
  9.26044, 9.4089, 9.33467,
  9.9195, 10.4757, 9.08897104,
  2.38, 0.24569895999999858,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  9.33467, 9.08897104, NULL,
  NULL, NULL, NULL,
  'loss', -2.63, 28,
  '2026-03-04T12:00:00+00:00', '2026-03-04T12:00:00+00:00', '2026-03-07T12:00:00+00:00', '2026-03-05T16:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  '3bc0f2f3-8ce8-4ea0-b4d8-ce2d37b45e80', 'LINK', 'buy', 'invalidated',
  9.11806, 9.29468, 9.20637,
  9.36958, 9.4089, 9.043687300000002,
  1.0, 0.16268269999999774,
  TRUE, '{"wick_rejection": false, "volume_spike": true, "consecutive_closes": false}'::jsonb, TRUE,
  9.20637, 9.043687300000002, NULL,
  NULL, NULL, NULL,
  'loss', -1.77, 24,
  '2026-03-05T12:00:00+00:00', '2026-03-05T12:00:00+00:00', '2026-03-08T12:00:00+00:00', '2026-03-06T12:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

INSERT INTO trade_signals (
  id, asset, signal_type, status,
  entry_zone_low, entry_zone_high, entry_price_mid,
  target_1, target_2, stop_loss,
  risk_reward_ratio, risk_1r,
  bounce_confirmed, confirmation_details, ema_trend_aligned,
  best_price, runner_stop, runner_exit_price,
  t1_hit_at, t1_pnl_pct, runner_pnl_pct,
  outcome, outcome_pct, duration_hours,
  generated_at, triggered_at, expires_at, closed_at
) VALUES (
  'd16e75d4-23f7-4740-96fc-c2263523c268', 'ADA', 'sell', 'invalidated',
  0.2611114, 0.26700820000000003, 0.2640598,
  0.2560642, 0.251633, 0.26915023559999995,
  1.57, 0.005090435599999943,
  TRUE, '{"wick_rejection": true, "volume_spike": false, "consecutive_closes": false}'::jsonb, TRUE,
  0.2640598, 0.26915023559999995, NULL,
  NULL, NULL, NULL,
  'loss', -1.93, 8,
  '2026-03-04T00:00:00+00:00', '2026-03-04T00:00:00+00:00', '2026-03-07T00:00:00+00:00', '2026-03-04T08:00:00+00:00'
) ON CONFLICT (id) DO NOTHING;

