import { createClient } from "https://esm.sh/@supabase/supabase-js@2"

/**
 * generate-signal-briefing Edge Function
 *
 * Called after a new trade signal is generated by fibonacci-pipeline.
 * Uses Claude API to generate a natural language briefing for the signal.
 *
 * Expects POST body: { signal_id: string }
 * Auth: x-cron-secret header (system-to-system call)
 */

Deno.serve(async (req) => {
  if (req.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405)
  }

  const secret = req.headers.get("x-cron-secret") ?? ""
  const expectedSecret = Deno.env.get("CRON_SECRET") ?? ""
  if (!expectedSecret || secret !== expectedSecret) {
    return jsonResponse({ error: "Unauthorized" }, 401)
  }

  const anthropicKey = Deno.env.get("ANTHROPIC_API_KEY")
  if (!anthropicKey) {
    return jsonResponse({ error: "ANTHROPIC_API_KEY not set" }, 500)
  }

  let signalId: string
  try {
    const body = await req.json()
    signalId = body.signal_id
  } catch {
    return jsonResponse({ error: "Invalid request body" }, 400)
  }

  if (!signalId) {
    return jsonResponse({ error: "Missing signal_id" }, 400)
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL") ?? "",
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? "",
  )

  // Fetch the signal
  const { data: signal, error: sigErr } = await supabase
    .from("trade_signals")
    .select("*, fib_confluence_zones!confluence_zone_id(contributing_levels)")
    .eq("id", signalId)
    .single()

  if (sigErr || !signal) {
    return jsonResponse({ error: "Signal not found" }, 404)
  }

  // Build prompt data
  const confluenceLevels = signal.fib_confluence_zones?.contributing_levels ?? []

  // Map signal_type to compliant labels
  const signalTypeLabel: Record<string, string> = {
    strong_buy: "Strong Long Setup",
    buy: "Long Setup",
    strong_sell: "Strong Short Setup",
    sell: "Short Setup",
  }
  const setupLabel = signalTypeLabel[signal.signal_type] ?? signal.signal_type

  const signalData = `
- Asset: ${signal.asset}
- Setup type: ${setupLabel}
- Pattern entry zone: $${Number(signal.entry_zone_low).toLocaleString()} - $${Number(signal.entry_zone_high).toLocaleString()}
- Target 1: $${signal.target_1 ? Number(signal.target_1).toLocaleString() : "N/A"}
- Target 2: $${signal.target_2 ? Number(signal.target_2).toLocaleString() : "N/A"}
- Stop loss: $${Number(signal.stop_loss).toLocaleString()}
- Risk/reward: ${signal.risk_reward_ratio}x
- Confluence details: ${JSON.stringify(confluenceLevels)}
- BTC risk score: ${signal.btc_risk_score ?? "N/A"}
- Fear & Greed: ${signal.fear_greed_index ?? "N/A"}
- Macro regime: ${signal.macro_regime ?? "N/A"}
- Coinbase ranking: ${signal.coinbase_ranking ? `#${signal.coinbase_ranking}` : "N/A"}
- Bounce confirmation: ${JSON.stringify(signal.confirmation_details ?? {})}
`.trim()

  try {
    const claudeResponse = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": anthropicKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 600,
        system: `You are Arkline's pattern analysis engine. Generate a concise educational briefing describing the detected Fibonacci pattern conditions. This is a pattern observation tool, NOT trading advice. Format the output as a JSON object with these fields:
- headline (max 60 chars, e.g. "BTC Fibonacci Confluence at Key Support — Long Setup Detected")
- summary (2-3 sentences describing the pattern setup and what conditions have aligned. Frame as observations: "conditions detected", "pattern suggests", "levels are aligning". Never say "buy", "sell", "time to enter", or give action directives.)
- supporting_signals (array of 2-3 short bullet point strings highlighting the strongest confirming data points as observations)
- disclaimer ("This is not financial advice. These are pattern observations for educational purposes. Always DYOR and consult a licensed advisor before making crypto-related decisions.")

IMPORTANT language rules:
- Use "Long Setup" / "Short Setup" instead of "Buy" / "Sell"
- Use "pattern entry zone" or "setup zone" instead of "entry point"
- Frame everything as pattern observations, not recommendations
- Never say "time to buy/sell", "you should", "we recommend", or similar action directives
- End with context, not a call to action

Return ONLY the JSON object, no markdown fences or extra text.`,
        messages: [
          {
            role: "user",
            content: `Generate a pattern analysis briefing from this data:\n\n${signalData}`,
          },
        ],
      }),
    })

    if (!claudeResponse.ok) {
      const errorText = await claudeResponse.text()
      console.error(`Claude API error: ${claudeResponse.status} ${errorText}`)
      return jsonResponse({ error: "Briefing generation failed" }, 502)
    }

    const claudeData = await claudeResponse.json()
    const rawText: string = claudeData.content?.[0]?.text ?? ""

    // Parse the JSON response
    let briefing: Record<string, unknown>
    try {
      briefing = JSON.parse(rawText)
    } catch {
      // If Claude didn't return valid JSON, store raw text
      briefing = { headline: signal.signal_type.toUpperCase(), summary: rawText, disclaimer: "" }
    }

    // Build the briefing text for storage
    const briefingText = [
      briefing.headline,
      "",
      briefing.summary,
      "",
      ...(Array.isArray(briefing.supporting_signals)
        ? (briefing.supporting_signals as string[]).map((s) => `• ${s}`)
        : []),
      "",
      briefing.disclaimer ?? "",
    ].join("\n").trim()

    // Update the signal with the briefing
    const { error: updateErr } = await supabase
      .from("trade_signals")
      .update({ briefing_text: briefingText })
      .eq("id", signalId)

    if (updateErr) {
      console.error("Failed to save briefing:", updateErr.message)
      return jsonResponse({ error: "Failed to save briefing" }, 500)
    }

    return jsonResponse({ success: true, briefing: briefingText })
  } catch (err) {
    console.error("Briefing generation failed:", String(err))
    return jsonResponse({ error: "Internal error" }, 500)
  }
})

function jsonResponse(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json" },
  })
}
